"""
包含数据库信息，调试标志，静态文件等配置
Django settings for django_f project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
# BASE_DIR表示的是项目的路径（我当前项目在虚拟机里或者系统里的一个路径）
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^%%5a9i6%_ga8s#-d)bz%kw+-8h0ama+f^1y90+-js*2*4loz('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

'''允许访问的客户端的地址, “*”表示的就是任意的ip地址'''
ALLOWED_HOSTS = ['*']


# Application definition
# 把自己新建的APP目录名字添加到INSTALLED_APPS
# INSTALLED_APPS指的是把我们新建的APP目录进行注册
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    '第3章',                 #模板目录和静态目录在项目目录下建的，就要注册
    '第4章',
    'common',
    'Database',
    '表关系',
    '博客',
    'request_response',
    'cookie_session',
    'login_register',
]
# 中间件
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #注册自定义的中间件的类
    'django_f.mymiddleware.Middleware',
    'django_f.mymiddleware.UserMiddleware',
    'django_f.mymiddleware.MyException',
]

ROOT_URLCONF = 'django_f.main_urls'
# 配置模板文件templates路径
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #
        'DIRS': [os.path.join(BASE_DIR,'templates')],   #拼接路径即可，就可以使用templates文件夹啦
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 注册自定义的上下文处理器
                'django_f.mycontext.myuser'
            ],
        },
    },
]

WSGI_APPLICATION = 'django_f.wsgi.application'

# 配置数据库路径以及基本信息
# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 数据库引擎
        # 'NAME': 'bk_db',                #(博客的数据库)
        # 'NAME': 'django_test',        #(表关系的数据库,在命令行里执行的数据库)
        'NAME': 'django_sqls',             #数据库名称   (表关系的数据库)
        'USER': 'admin',                 # 链接数据库的用户名
        'PASSWORD': 'Root110qwe',         # 链接数据库的密码
        'HOST': '192.168.216.128',             # mysql服务器的域名和ip地址
        'PORT': '3306',                  # mysql的一个端口号,默认是3306
    }
}



# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/
# 编码设置
# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-Hans'  #汉语
'''时区设置'''
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
'''方法1 ：这是把静态文件放在项目目录下（和子APP同级的目录）的静态文件目录，要设置的路径'''
# 一个是设置url
STATIC_URL = '/static/'

# 一个是设置项目的文件路径
STATICFILES_DIRS=[os.path.join(BASE_DIR,'static')]

# 上传文件存放的路径,media是自己创建的目录名，要设置上传文件的话就要设置这个MEDIA_ROOT
MEDIA_ROOT=os.path.join(BASE_DIR,'request_response/static/media')

'''设置会话过期时间'''
# 是否关闭浏览器使得Session过期，默认是False
SESSION_EXPIRE_AT_BROWSER_CLOSE=False
# 是否每次请求都保存Session,默认修改之后才保存
SESSION_SAVE_EVERY_REQUEST=False
# Session的cookie失效日期，默认是2周
SESSION_COOKIE_AGE=1209600