# Generated by Django 2.1.2 on 2018-11-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='北京', max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='note',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
