# Generated by Django 2.1.2 on 2018-11-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_auto_20181109_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ftest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('age', models.IntegerField()),
                ('note', models.TextField()),
                ('gender', models.BooleanField(default=True)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('updata_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
