# Generated by Django 2.1.2 on 2018-11-10 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=30)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='表关系.Department')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('sd_id', models.AutoField(primary_key=True, serialize=False)),
                ('sd_age', models.IntegerField()),
                ('sd_gender', models.BooleanField()),
                ('sd_addr', models.CharField(max_length=30, null=True)),
                ('s_sd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='表关系.Student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course',
            field=models.ManyToManyField(to='表关系.Student'),
        ),
    ]
