# Generated by Django 2.1.2 on 2018-11-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('表关系', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='student',
        ),
    ]
