# Generated by Django 2.1.2 on 2018-11-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('表关系', '0002_auto_20181110_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetail',
            name='sd_addr',
        ),
    ]
